### ISSUE TITLE
Triggering a repaint is too hard

### ISSUE THREAD

**Issue by flying-sheep** [unconed/MathBox.js#27]
Hi, I’m currently merging MathBox.js and Reveal.js for a personal talk, and hope to get a Reveal.js plugin out of it.

Unfortunately, I had to dig deep and ugly to get things to work if the slide MathBox is on is made visible too late:

``` javascript
var mathbox = …
  , slide = …

Reveal.addEventListener('slidechanged', function(e) {
    if (e.currentSlide === slide) {
        var ctx = tQuery.data(mathbox.world(), '_threeBoxContext')
        ctx.elementResize.callback()
    }
})
```

It would be nice if there was some `mathbox.update()` call doing this for me.

PS: the ThreeBox repo says it’s dead – Is there some MathBox 2 without it in the works or something?

PPS: What the plugin allows to do will be simply a way to hook MathBox’ Director into Reveal.js’ fragment system, so that any next- or previous-command for Reveal.js will do the right thing.

**Comment by eric-wieser** [comment]
> For my own talks, I always embedded each mathbox slideshow as an iframe, synced to the parent slideshow, it was easier and more robust.

For anyone coming here via a google search for mathbox and reveal.js, here's how I managed to do that with `reveal.js` (for mathbox 2):

```html
<section data-background-iframe="mathbox-frame.html">
    <section></section> <!-- one of these for each step in mathbox - useful for speaker notes if nothing else -->
</section>
```
```javascript
var updateIframe = function (inds, el) {
	var bg = Reveal.getSlideBackground(inds.h);
	var iframe = bg.querySelector('iframe');
	if (!el || el == iframe) {
		iframe.contentWindow.postMessage(JSON.stringify({
			namespace: 'reveal', eventName: 'slide', value: inds.v
		}), '*');
	}
};
// update mathbox when the step changes
Reveal.addEventListener( 'slidechanged', function(e) {
	updateIframe(Reveal.getIndices(e.currentSlide));
});
// the above won't be received by iframes that aren't loaded
Reveal.addEventListener( 'ready', function() {
	Array.from(document.querySelectorAll('iframe')).forEach(function(el) {
		el.addEventListener('load', function() {
			updateIframe(Reveal.getIndices(), el);
		});
	});
});
```
And in your mathbox frame:
```javascript
window.addEventListener('message', function(e) {
  e = JSON.parse(e.data);
  if(e.eventName == 'slide') {
    present.set('index', e.value);
  }
});
```
